default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: utf8mb4
  strict: false

test:
  <<: *default
  host: <%= Rails.application.credentials.mysql[:test][:host] %>
  port: <%= Rails.application.credentials.mysql[:test][:port] %>
  username: <%= Rails.application.credentials.mysql[:test][:username] %>
  password: <%= Rails.application.credentials.mysql[:test][:password] %>
  database: <%= Rails.application.credentials.mysql[:test][:database] %>

development:
  <<: *default
  host: <%= Rails.application.credentials.mysql[:development][:host] %>
  port: <%= Rails.application.credentials.mysql[:development][:port] %>
  username: <%= Rails.application.credentials.mysql[:development][:username] %>
  password: <%= Rails.application.credentials.mysql[:development][:password] %>
  database: <%= Rails.application.credentials.mysql[:development][:database] %>

production:
  <<: *default
  host: <%= Rails.application.credentials.mysql[:production][:host] %>
  port: <%= Rails.application.credentials.mysql[:production][:port] %>
  username: <%= Rails.application.credentials.mysql[:production][:username] %>
  password: <%= Rails.application.credentials.mysql[:production][:password] %>
  database: <%= Rails.application.credentials.mysql[:production][:database] %>
