default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: utf8mb4
  strict: false

test:
  <<: *default
  host: <%= ENV['MYSQL_HOST_TEST'] || Rails.application.credentials.mysql[:test][:host] %>
  port: <%= ENV['MYSQL_PORT_TEST'] || Rails.application.credentials.mysql[:test][:port] %>
  username: <%= ENV['MYSQL_USERNAME_TEST'] || Rails.application.credentials.mysql[:test][:username] %>
  password: <%= ENV['MYSQL_PASSWORD_TEST'] || Rails.application.credentials.mysql[:test][:password] %>
  database: <%= ENV['MYSQL_DATABASE_TEST'] || Rails.application.credentials.mysql[:test][:database] %>

development:
  <<: *default
  host: <%= ENV['MYSQL_HOST_DEVELOPMENT'] || Rails.application.credentials.mysql[:development][:host] %>
  port: <%= ENV['MYSQL_PORT_DEVELOPMENT'] || Rails.application.credentials.mysql[:development][:port] %>
  username: <%= ENV['MYSQL_USERNAME_DEVELOPMENT'] || Rails.application.credentials.mysql[:development][:username] %>
  password: <%= ENV['MYSQL_PASSWORD_DEVELOPMENT'] || Rails.application.credentials.mysql[:development][:password] %>
  database: <%= ENV['MYSQL_DATABASE_DEVELOPMENT'] || Rails.application.credentials.mysql[:development][:database] %>

production:
  <<: *default
  host: <%= ENV['MYSQL_HOST_PRODUCTION'] || Rails.application.credentials.mysql[:production][:host] %>
  port: <%= ENV['MYSQL_PORT_PRODUCTION'] || Rails.application.credentials.mysql[:production][:port] %>
  username: <%= ENV['MYSQL_USERNAME_PRODUCTION'] || Rails.application.credentials.mysql[:production][:username] %>
  password: <%= ENV['MYSQL_PASSWORD_PRODUCTION'] || Rails.application.credentials.mysql[:production][:password] %>
  database: <%= ENV['MYSQL_DATABASE_PRODUCTION'] || Rails.application.credentials.mysql[:production][:database] %>
