##default: &default
##  adapter: mysql2 # <%= Rails.application.credentials.mysql[:default][:adapter] %> # mysql2
###  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
##  timeout: 5000
##  encoding: utf8mb4 # <%= Rails.application.credentials.mysql[:default][:encoding] %> # utf8mb4
#
#development:
#  adapter: sqlite3
#  database: db/development.sqlite3
#  pool: 5
#  timeout: 5000
#
##  <<: *default
##  host: <%= Rails.application.credentials.mysql[:development][:host] %>
##  port: <%= Rails.application.credentials.mysql[:development][:port] %>
##  username: <%= Rails.application.credentials.mysql[:development][:username] %>
##  password: <%= Rails.application.credentials.mysql[:development][:password] %>
##  database: <%= Rails.application.credentials.mysql[:development][:database] %>
#
#test:
#  <<: *default
#  database: sosenkyo_2018_test
#
#production:
#  <<: *default
#  database: sosenkyo_2018_production
#

# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000