default: &default
  adapter: <%= Rails.application.credentials.mysql_sub[:default][:adapter] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: <%= Rails.application.credentials.mysql_sub[:default][:encoding] %>

development:
  <<: *default
  host: <%= Rails.application.credentials.mysql_sub[:development][:host] %>
  port: <%= Rails.application.credentials.mysql_sub[:development][:port] %>
  username: <%= Rails.application.credentials.mysql_sub[:development][:username] %>
  password: <%= Rails.application.credentials.mysql_sub[:development][:password] %>
  database: <%= Rails.application.credentials.mysql_sub[:development][:database] %>

test:
  <<: *default
  database: gss48_test

production:
  <<: *default
  database: gss48_production
