on: [push]
name: Suikoden Election 2018
jobs:
  suikoden_election_2018_github_actions:
    name: Suikoden Election 2018 CI
    runs-on: ubuntu-latest
    container:
      image: ruby:2.6.6
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: bundle install
